name: Update APT Repository

on:
  workflow_dispatch:

  push:
    paths:
      - 'packages.list'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y reprepro gnupg wget

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Fetch Packages
      run: |
        mkdir -p downloaded_packages
        ./scripts/fetch-packages.sh

    - name: Build Repo
      run: |
        ./scripts/setup-reprepro.sh

    - name: Upload APT Repo to Aliyun OSS
      uses: fangbinwei/aliyun-oss-website-action@v1
      with:
        accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
        accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
        bucket: ${{ secrets.ACCESS_BUCKET_NAME }}
        endpoint: oss-cn-shanghai.aliyuncs.com
        folder: ./gh-pages

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
        keep_files: false